volumes:
  pg-store:

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password0#
      PGPASSWORD: password
      POSTGRES_DB: dev
      TZ: "Asia/Tokyo"
    volumes:
      - ./pg-store:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: development@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 88:80
    depends_on:
      - postgres
